Game:

<Game>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        Label:
            size_hint_y: 0.7
            id: label1
            font_size: 30
            text: root.text
            color: root.color
            font_name: 'msgothic.ttc'

        Button:
            id: button1
            text: "ボタン"
            font_size: 24
            on_press: root.buttonClicked()
            font_name: 'msgothic.ttc'
